apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kanidm-ingress
  annotations:
    {% for key, value in annotations.items() %}
    {{ key }}: {{ value }}
    {% endfor %}
    {% if ingress_controller == "caddy" and "kubernetes.io/ingress.class" not in annotations%}
    kubernetes.io/ingress.class: caddy
    {% endif %}
    {% if ingress_controller == "nginx" and "kubernetes.io/ingress.class" not in annotations%}
    kubernetes.io/ingress.class: nginx
    {% endif %}
    cert-manager.io/cluster-issuer: {{ certificate_issuer }}
spec:
  tls:
  - hosts:
    - {{ hostname }}
    secretName: kanidm-cert-prod
  rules:
  - host: {{ hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kanidm-svc
            port:
              number: {{ http_port }}
